def cask(name); dep name, :template => "icelab:cask"; end # Avoid repitition below

cask "dash"
cask "fork"
cask "google-chrome"
cask "imageoptim"
cask "iterm2"
cask "launchbar"
cask "licecap"
cask "postico"
cask "slack"
cask "sublime-text"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
